spring:
  application:
    name: microserver-config-client
    
eureka:
  client:
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    hostname: config8004.com
    prefer-ip-address: true
    instance-id: microserver-config-client
server:
  port: 8004
  
